version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
  mlflow:
    image: mlflow/mlflow
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri /mlflow --default-artifact-root /mlflow/artifacts
    volumes:
      - ./mlflow:/mlflow
