name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r backend/app/requirements.txt

      - name: Run tests
        run: |
          echo "Add your backend tests here"

      - name: Build Docker image
        run: |
          docker build -t gemma-chatbot:latest backend/app
